package se.ernberg.components.zoomableimage;

import javax.swing.JButton;
import javax.swing.JPanel;

public class ZoomableImageStandardToolbar extends JPanel{

	/**
	 * Generated by eclipse
	 */
	private static final long serialVersionUID = 4903502806667662866L;

	public ZoomableImageStandardToolbar(ZoomableImage zoomableImage) {
		// Add buttons for the different actions provided by ZoomableImage
		add(new JButton(zoomableImage.ACTION_RESET));
		add(new JButton(zoomableImage.ACTION_ZOOM_IN));
		add(new JButton(zoomableImage.ACTION_ZOOM_OUT));
		add(new JButton(zoomableImage.ACTION_FIT_PANE));
		add(new JButton(zoomableImage.ACTION_FILL_PANE));
		add(new JButton(zoomableImage.ACTION_ORIGINAL_SIZE));
	}

}
